export const allTopics = {
  Evs: {
    1: [
      "Me and My family",
      "Small,Large and Joint Family",
      "My Home",
      "My Body",
      "Food We Eat",
      "Good Habits and Cleanliness",
      "The World of Plants",
      "Animals and birds",
    ],
    2: [
      "Our Environment",
      "Plants and their Uses",
      "Animals Around Us",
      "Cleanliness Around Us",
      "Safety and First Aid",
      "Types of Houses",
      "Seasons",
    ],
  },
  Science: {
    3: [
      "Eating habits of Animals",
      "Keeping Safe",
      "Housing and Clothing",
      "Soil",
      "Solids,Liquids and Gases",
      "Living and Non living things",
      "Parts of a plant",
      "Birds",
      "Our Body",
      "Measurement",
      "Light, Sound and Force",
      "Air,Water and Weather",
      "The Sun,Moon and Stars",
      "Our Earth",
    ],
    4: [
      "Food: Our Basic Need",
      "Digestion and the Role of Microbes",
      "Clothes We Wear",
      "Solids,Liquids and Gases",
      "Soil",
      "The Green Plants",
      "How Plants Survive",
      "Circulatory System and Excretory System",
      "Animals and their young ones",
      "How Animals Survive",
      "Force, Work, and Energy",
      "Air, Water, and Weather",
      "The Solar System",
      "Keeping Our Earth Green",
    ],
    5: [
      "Growing Plants",
      "Food and Health",
      "Safety and First Aid",
      "Solids,Liquids and Gases",
      "Rocks and Minerals",
      "Animals: Habitat and Adaptation",
      "Skeletal System and Nervous System",
      "Measurement",
      "Force and Energy",
      "Air and Water",
      "Earth Sun and Moon",
      "Light and Shadow",
      "Volcanoes,Earthquakes and Tidal Waves",
      "Our Environment",
    ],
    6: [
      "Components of Food",
      "Sorting Materials into Groups",
      "Separation of Substances",
      "Getting to Know Plants",
      "Body Movements",
      "The Living Organisms and Their Surroundings",
      "Motion and Measurement of Distances",
      "Light, Shadows, and Reflections",
      "Electricity and Circuits",
      "Fun with Magnets",
      "Water",
      "Air Around Us",
    ],
    7: [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Heat",
      "Acids, Bases, and Salts",
      "Physical and Chemical Changes",
      "Weather, Climate, and Adaptations of Animals",
      "Winds, Storms, and Cyclones",
      "Soil",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Reproduction in Plants",
      "Motion and Time",
      "Electric Current and Its Effects",
      "Light",
      "Forests: Our Lifeline",
      "Wastewater Story",
    ],
    8: [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Synthetic Fibres and Plastics",
      "Materials: Metals and Non-Metals",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Cell: Structure and Functions",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Force and Pressure",
      "Friction",
      "Sound",
      "Chemical Effects of Electric Current",
      "Some Natural Phenomena",
      "Light",
      "Stars and the Solar System",
      "Pollution of Air and Water",
    ],
    9: [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure?",
      "Atoms and Molecules",
      "Structure of the Atom",
      "The Fundamental Unit of Life",
      "Tissues",
      "Diversity in Living Organisms",
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound",
      "Why Do We Fall Ill?",
      "Natural Resources",
      "Improvement in Food Resources",
    ],
    10: [
      "Chemical Reactions and Equations",
      "Acids, Bases, and Salts",
      "Metals and Non-Metals",
      "Carbon and Its Compounds",
      "Periodic Classification of Elements",
      "Life Processes",
      "Control and Coordination",
      "How Do Organisms Reproduce?",
      "Heredity and Evolution",
      "Light: Reflection and Refraction",
      "Human Eye and Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Sources of Energy",
      "Our Environment",
      "Management of Natural Resources",
    ],
    11: [
      "Physical World",
      "Units and Measurements",
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Laws of Motion",
      "Work, Energy, and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory",
      "Oscillations",
      "Waves",
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "States of Matter: Gases and Liquids",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "Hydrogen",
      "s-Block Elements",
      "Some p-Block Elements",
      "Organic Chemistry: Some Basic Principles and Techniques",
      "Hydrocarbons",
      "Environmental Chemistry",

      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Structural Organisation in Animals",
      "Cell: The Unit of Life",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Digestion and Absorption",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and Their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration",
    ],
    12: [
      "Electric Charges and Fields",
      "Electrostatic Potential and Capacitance",
      "Current Electricity",
      "Moving Charges and Magnet",
    ],
  },
  Maths: {
    1: [
      "Pre-number concepts",
      "Numbers from 1 to 9 and 0",
      "Numbers up to 20",
      "Comparison of Numbers",
      "Subtraction",
      "Numbers up to 50",
      "Numbers up to 100",
      "Addition",
      "Subtraction",
    ],
    2: [
      "Numbers upto 1000",
      "Place Value",
      "Addition",
      "Subtraction",
      "Shapes and Patterns",
      "Money",
      "Time",
    ],
    3: [
      "Numbers",
      "Addition",
      "Subtraction",
      "Multiplication",
      "Shapes and Patterns",
      "Understanding Division",
      "Fractions",
      "Money",
      "Time",
      "Measurements",
      "Handling Data",
    ],
    4: [
      "Large Numbers",
      "Addition and Subtraction",
      "Multiplication",
      "Division",
      "Multiples and Factors",
      "Geometry",
      "Symmetry and Patterns",
      "Fractions",
      "Decimal Numbers",
      "Money",
      "Measurements",
      "Perimeter and Area",
      "Time",
      "Handling Data",
    ],
    5: [
      "Large Numbers",
      "Addition,Subtraction and their Applications",
      "Multiplication,Division and their Applications",
      "Factors and Multiples",
      "Fractions",
      "Decimal Numbers",
      "Measurements",
      "Perimeter,Area and Volume",
      "Time,Speed and Temperature",
      "Maths in Maps",
      "Area and its Boundary",
      "Symmetry Patterns and Nets",
    ],
    6: [
      "Knowing Our Numbers",
      "Whole Numbers",
      "Playing with Numbers",
      "Basic Geometrical Ideas",
      "Understanding Elementary Shapes",
      "Integers",
      "Fractions",
      "Decimals",
      "Data Handling",
      "Mensuration",
      "Algebra",
      "Ratio and Proportion",
    ],
    7: [
      "Integers",
      "Fractions and Decimals",
      "Data Handling",
      "Simple Equations",
      "Lines and Angles",
      "The Triangle and Its Properties",
      "Comparing Quantities",
      "Rational Numbers",
      "Practical Geometry",
      "Perimeter and Area",
      "Algebraic Expressions",
      "Exponents and Powers",
      "Symmetry",
      "Visualising Solid Shapes",
    ],
    8: [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Understanding Quadrilaterals",
      "Practical Geometry",
      "Data Handling",
      "Squares and Square Roots",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Visualising Solid Shapes",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorisation",
      "Introduction to Graphs",
      "Playing with Numbers",
    ],
    9: [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
      "Linear Equations in Two Variables",
      "Introduction to Euclid's Geometry",
      "Lines and Angles",
      "Triangles",
      "Quadrilaterals",
      "Areas of Parallelograms and Triangles",
      "Circles",
      "Constructions",
      "Heron's Formula",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
    10: [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Constructions",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
    11: [
      "Sets",
      "Relations and Functions",
      "Trigonometric Functions",
      "Principle of Mathematical Induction",
      "Complex Numbers and Quadratic Equations",
      "Linear Inequalities",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequences and Series",
      "Straight Lines",
      "Conic Sections",
      "Introduction to Three-dimensional Geometry",
      "Limits and Derivatives",
      "Mathematical Reasoning",
      "Statistics",
      "Probability",
    ],
    12: [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Applications of Derivatives",
      "Integrals",
      "Applications of Integrals",
      "Differential Equations",
      "Vectors",
      "Three-dimensional Geometry",
      "Linear Programming",
      "Probability",
    ],
  },
  SS: {
    3: [
      "Our Universe",
      "The Earth-Its Surface and Movements",
      "Continents and Oceans",
      "Using Directions",
      "Weather,Seasons and Climate",
      "India-Physical",
      "India-Political",
      "Sources of History and Timelines",
      "The Story of the Earliest People",
      "Fire,Farming and the Wheel",
      "The Egpytian Civlisation",
      "The Indus Valley Civlisaiton",
      "Our Neighbourhood",
      "Being Good and Being Safe",
      "Transport and Communication",
      "My India - Food and Clothes",
      "My India - Festival and Dance",
      "National Symbols",
      "Our Government",
      "New Delhi",
      "Mumbai",
      "Kolkata",
      "Chennai",
    ],
    4: [
      "Globes and Maps",
      "Our Country and its neighbours",
      "The Northern Mountains and the Northern Plains",
      "The Plateau an the Desert Regions",
      "The Coastal Plains and the Islands",
      "The Climate of India",
      "Our Natural Resource: Forests and Wildlife",
      "Our Natural Resource: Water and Soils",
      "Agriculture and Minerals",
      "Our Industries",
      "Our Heritage",
      "Our History",
      "Emperor Akbar",
      "Emperor Shah Jahan",
      "Chhatrapati Shivaji Maharaj",
      "Transport and Commuication",
      "Organizations that help us",
      "Local Self-Government",
      "Elections",
      "Celebrating Together",
    ],
    5: [
      "Our Earth,Continents and Oceans",
      "The Imaginary Lines: Latitude and Longitude",
      "Movements of Earth: their Effects",
      "Temperature Zones of the world",
      "The Equatorial Forest Region",
      "The Hot Deserts",
      "The Temperate Zone",
      "The Frigid Zone",
      "Our Environment",
      "Pollution",
      "How to Conserve our Environment",
    ],
    6: [
      "Understading Diversity",
      "Diversity and Discrimination",
      "What is Government",
      "Key Elements of a Democractic Government",
      "Panchayati Raj",
      "Rural Administration",
      "Urban Administration",
      "Rural Livelihoods",
      "Urban Livelihoods",
    ],
    7: [
      "Environment",
      "Inside Our Earth",
      "Our Changing Earth",
      "Air",
      "Water",
      "Human Environment Interactions",
      "Life in the Deserts",
      "On Equality",
      "Role of the Government in Health",
      "How the State Government Works",
      "Growing up as boys and girls",
      "Women Change the World",
      "Understanding Media",
      "Markets Around Us",
      "A Shirt in the Market",
      "Tracing Changes through a thousand years",
      "New Kings and Kingdoms",
      "The Delhi Sultans",
      "The Mughal Empire",
      "Rulers and Buildings",
      "Towns,Traders and Craftspersons",
      "Tribe, Nomad and Settled Communities",
      "Devotional Path to the divine",
      "The Making of Regional Cultures",
      "Eighteenth Century Political Formations",
    ],
  },
};
