export const 
allTopics = {
  science: {
    1: [
      "Living and Non-Living Things",
      "Plants Around Us",
      "Animals Around Us",
      "Our Body",
      "Food We Eat",
      "Shelter",
      "Water",
      "Travel and Communication",
      "Weather and Seasons",
      "Sky and Earth",
    ],
    2: [
      "Our Body",
      "Plants",
      "Animals",
      "Air",
      "Water",
      "Weather",
      "The Earth and the Sky",
      "Our Environment",
    ],
    3: [
      "Living and Non-Living",
      "Parts of a Plant",
      "Birds",
      "Our Body",
      "Safety and First Aid",
      "Housing and Clothing",
      "Soil",
      "Solids, Liquids, and Gases",
      "Light, Sound, and Force",
      "Work and Play",
      "Our Environment",
    ],
    4: [
      "Food and Digestion",
      "Teeth and Microbes",
      "Safety First",
      "The Right Clothes to Wear",
      "Solids, Liquids, and Gases",
      "Plants: Preparing and Storing Food",
      "Plants: Living and Surviving",
      "Animals: How Life Goes On",
      "Animals: Living and Surviving",
      "Force, Work, and Energy",
      "The Earth and Its Neighbours",
      "Air, Water, and Weather",
      "A Clean World",
    ],
    5: [
      "Reproduction in Plants",
      "Animals and Their Young Ones",
      "Bones and Muscles",
      "The Nervous System",
      "Food and Health",
      "Safety and First Aid",
      "Rocks and Minerals",
      "Soil Erosion and Conservation",
      "Our Environment",
      "Natural Calamities",
      "Simple Machines",
      "The Moon",
      "Changes in Our Environment",
    ],
    6: [
      "Food: Where Does It Come From?",
      "Components of Food",
      "Fibre to Fabric",
      "Sorting Materials into Groups",
      "Separation of Substances",
      "Changes Around Us",
      "Getting to Know Plants",
      "Body Movements",
      "The Living Organisms and Their Surroundings",
      "Motion and Measurement of Distances",
      "Light, Shadows, and Reflections",
      "Electricity and Circuits",
      "Fun with Magnets",
      "Water",
      "Air Around Us",
      "Garbage In, Garbage Out",
    ],
    7: [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Fibre to Fabric",
      "Heat",
      "Acids, Bases, and Salts",
      "Physical and Chemical Changes",
      "Weather, Climate, and Adaptations of Animals",
      "Winds, Storms, and Cyclones",
      "Soil",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Reproduction in Plants",
      "Motion and Time",
      "Electric Current and Its Effects",
      "Light",
      "Water: A Precious Resource",
      "Forests: Our Lifeline",
      "Wastewater Story",
    ],
    8: [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Synthetic Fibres and Plastics",
      "Materials: Metals and Non-Metals",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Cell: Structure and Functions",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Force and Pressure",
      "Friction",
      "Sound",
      "Chemical Effects of Electric Current",
      "Some Natural Phenomena",
      "Light",
      "Stars and the Solar System",
      "Pollution of Air and Water",
    ],
    9: [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure?",
      "Atoms and Molecules",
      "Structure of the Atom",
      "The Fundamental Unit of Life",
      "Tissues",
      "Diversity in Living Organisms",
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound",
      "Why Do We Fall Ill?",
      "Natural Resources",
      "Improvement in Food Resources",
    ],
    10: [
      "Chemical Reactions and Equations",
      "Acids, Bases, and Salts",
      "Metals and Non-Metals",
      "Carbon and Its Compounds",
      "Periodic Classification of Elements",
      "Life Processes",
      "Control and Coordination",
      "How Do Organisms Reproduce?",
      "Heredity and Evolution",
      "Light: Reflection and Refraction",
      "Human Eye and Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Sources of Energy",
      "Our Environment",
      "Management of Natural Resources",
    ],
    11: [
      "Physical World",
      "Units and Measurements",
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Laws of Motion",
      "Work, Energy, and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory",
      "Oscillations",
      "Waves",
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "States of Matter: Gases and Liquids",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "Hydrogen",
      "s-Block Elements",
      "Some p-Block Elements",
      "Organic Chemistry: Some Basic Principles and Techniques",
      "Hydrocarbons",
      "Environmental Chemistry",

      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Structural Organisation in Animals",
      "Cell: The Unit of Life",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Digestion and Absorption",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and Their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration",
    ],
    12: [
      "Electric Charges and Fields",
      "Electrostatic Potential and Capacitance",
      "Current Electricity",
      "Moving Charges and Magnet",
    ],
  },
  maths: {
    1: [
      "Shapes and Space",
      "Numbers from One to Nine",
      "Addition",
      "Subtraction",
      "Numbers from Ten to Twenty",
      "Time",
      "Measurement",
      "Numbers from Twenty-one to Fifty",
      "Data Handling",
      "Patterns",
      "Numbers",
      "Money",
      "How Many",
    ],
    2: [
      "What is Long, What is Round?",
      "Counting in Groups",
      "How Much Can You Carry?",
      "Counting in Tens",
      "Patterns",
      "Footprints",
      "Jugs and Mugs",
      "Tens and Ones",
      "My Funday",
      "Add our Points",
      "Lines and Lines",
      "Give and Take",
      "The Longest Step",
      "Birds Come, Birds Go",
      "How Many Ponytails?",
    ],
    3: [
      "Where to Look From",
      "Fun with Numbers",
      "Give and Take",
      "Long and Short",
      "Shapes and Designs",
      "Fun with Give and Take",
      "Time Goes On",
      "Who is Heavier?",
      "How Many Times?",
      "Play with Patterns",
      "Jugs and Mugs",
      "Can We Share?",
      "Smart Charts!",
      "Rupees and Paise",
    ],
    4: [
      "Building with Bricks",
      "Long and Short",
      "A Trip to Bhopal",
      "Tick-Tick-Tick",
      "The Way The World Looks",
      "The Junk Seller",
      "Jugs and Mugs",
      "Carts and Wheels",
      "Halves and Quarters",
      "Play with Patterns",
      "Tables and Shares",
      "How Heavy? How Light?",
      "Fields and Fences",
      "Smart Charts",
    ],
    5: [
      "The Fish Tale",
      "Shapes and Angles",
      "How Many Squares?",
      "Parts and Wholes",
      "Does it Look the Same?",
      "Be My Multiple, I'll be Your Factor",
      "Can You See the Pattern?",
      "Mapping Your Way",
      "Boxes and Sketches",
      "Tenths and Hundredths",
      "Area and its Boundary",
      "Smart Charts",
      "Ways to Multiply and Divide",
      "How Big? How Heavy?",
    ],
    6: [
      "Knowing Our Numbers",
      "Whole Numbers",
      "Playing with Numbers",
      "Basic Geometrical Ideas",
      "Understanding Elementary Shapes",
      "Integers",
      "Fractions",
      "Decimals",
      "Data Handling",
      "Mensuration",
      "Algebra",
      "Ratio and Proportion",
      "Symmetry",
      "Practical Geometry",
    ],
    7: [
      "Integers",
      "Fractions and Decimals",
      "Data Handling",
      "Simple Equations",
      "Lines and Angles",
      "The Triangle and Its Properties",
      "Congruence of Triangles",
      "Comparing Quantities",
      "Rational Numbers",
      "Practical Geometry",
      "Perimeter and Area",
      "Algebraic Expressions",
      "Exponents and Powers",
      "Symmetry",
      "Visualising Solid Shapes",
    ],
    8: [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Understanding Quadrilaterals",
      "Practical Geometry",
      "Data Handling",
      "Squares and Square Roots",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Visualising Solid Shapes",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorisation",
      "Introduction to Graphs",
      "Playing with Numbers",
    ],
    9: [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
      "Linear Equations in Two Variables",
      "Introduction to Euclid's Geometry",
      "Lines and Angles",
      "Triangles",
      "Quadrilaterals",
      "Areas of Parallelograms and Triangles",
      "Circles",
      "Constructions",
      "Heron's Formula",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
    10: [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Constructions",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
    11: [
      "Sets",
      "Relations and Functions",
      "Trigonometric Functions",
      "Principle of Mathematical Induction",
      "Complex Numbers and Quadratic Equations",
      "Linear Inequalities",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequences and Series",
      "Straight Lines",
      "Conic Sections",
      "Introduction to Three-dimensional Geometry",
      "Limits and Derivatives",
      "Mathematical Reasoning",
      "Statistics",
      "Probability",
    ],
    12: [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Applications of Derivatives",
      "Integrals",
      "Applications of Integrals",
      "Differential Equations",
      "Vectors",
      "Three-dimensional Geometry",
      "Linear Programming",
      "Probability",
    ],
  },
};
