export const chapterstoomit = [
  "chapter",
  "Thermodynamics",
  "Magnatic Effects of Electric Current",
  "current electricity",
  "electromagnetic induction",
  "Motion of System of Particles and Rigid Body",
  "Simple Harmonic Motion",
  "Properties of Bulk Matter",
  "Vectors and Dimensions",
  "Oscillations and Waves",
  "Nuclear Physics",
  "Communication Systems",
  "Kinematics",
  "Nuclei and Radioactivity",
  "Motion in a Straight Line and Projectile Motion",
  "Atoms",
  "Kinetic Theory of Gases",
  "Thermal Properties of Matter",
  "Vector Algebra",
  "Waves Optics",
  "Modern Physics",
  "Electronic Devices",
  "Alternating Current",
  "Experimental Skills",
  "Semiconductor ElectromicsMaterials, Devices and Simple Circuits",
  "Differential Equations",
  "Fluid Mechanics",
  "alternating current",
  "Law of Motion",
  "Geometrical Optics",
  "electrostatic potential and capacitance",
  "Work, Energy and Power",
  "atoms",
  "Electricity",
  "Magnetic Effects of Current and Magnetism",
  "Electromagnetic Waves",
  "Laws of Motion",
  "Current Electricity",
  "Circular Motion",
  "Rotational Motion",
  "Surface Tension",
  "Current Affairs",
  "Wave Nature of Electrons and Photons",
  "Center of Mass",
  "System of Particles and Rotational Motion",
  "Gravitation",
  "Magnetism and Matter",
  "Dual Nature of Radiation and Matter",
  "Electromagnetic Induction and Alternating Currents",
  "Ray Optics",
  "Properties of Solids and Liquids",
  "Properties of Fluids",
  "Dual Nature of Matter and Radiation",
  "dual nature of matter and radiation",
  "Electrostatics",
  "Electromagnetic Induction",
  "communication systems",
  "Electrostatic Potential and Capacitance",
  "magnetism and matter",
  "Atomic Models",
  "Errors and Measurements",
  "Projectile Motion",
  "Kinetic Theory",
  "wave optics",
  "Experimental skills",
  "semiconductor electronics: materials, devices and simple circuits",
  "electrostatic potental and capacitance",
  "Electrodynamics",
  "Atoms and Nuclei",
  "magnetic effects of electric current ",
  "Waves and Sound",
  "current electricity ",
  "magnetic effects of electric current",
  "Wave Optics",
  "ray optics",
  "Nucleus",
  "Atomic Structure",
  "Sound Waves",
  "electromagnetic waves",
  "nucleus",
  "Optics",
  "magnetic effect of electric current",
  "Kinetics and Collision",
  "Motion in a Plane",
  "Electricity and Magnetism",
  "Units and Measurements",
  "dual nature of radiation and matter",
  "Waves",
  "Capacitance",
  "chapter",
  "dynamics of a system of particles",
  "dynamics of system of particles",
  "fluid mechanics",
  "gavitation",
  "gravitation",
  "heat and transfer",
  "heat transfer",
  "kinetic theory of gases",
  "laws of motion",
  "mechanical properties of solid",
  "mechanical properties of solids",
  "motion in a plane",
  "motion in a straight line",
  "oscillations",
  "physical world",
  "rotational motion",
  "thermodynamics",
  "waves",
  "work energy and power",
];
