export const styles = {
  pageContainer: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: "#f4f6f9",
    minHeight: "100vh",
    padding: "20px",
  },
  plusIconContainer: {
    display: "flex",
    justifyContent: "center",
    marginTop: "10px",
  },

  plusButton: {
    backgroundColor: "#2ecc71",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "40px",
    height: "40px",
    fontSize: "20px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  descriptiveConfigContainer: {
    marginTop: "20px",
    backgroundColor: "#f9f9fb",
    border: "1px solid #e0e4e8",
    borderRadius: "8px",
    padding: "15px",
  },
  descriptiveConfigTitle: {
    margin: "0 0 10px",
    color: "#2c3e50",
  },
  descriptiveConfigRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "10px",
    alignItems: "flex-end",
  },
  descriptiveFieldGroup: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  
  container: {
    marginTop: 10,
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 4px 6px rgba(0,0,0,0.1)",
    padding: "30px",
  },
  formContainer: {
    display: "flex",
    gap: "30px",
    marginBottom: "30px",
  },
  columnLeft: {
    flex: 1,
  },
  columnRight: {
    flex: 1,
  },
  card: {
    backgroundColor: "white",
    border: "1px solid #e0e4e8",
    borderRadius: "8px",
    padding: "25px",
    boxShadow: "0 2px 4px rgba(0,0,0,0.05)",
  },
  cardTitle: {
    marginTop: 0,
    marginBottom: "20px",
    color: "#2c3e50",
    borderBottom: "2px solid #3498db",
    paddingBottom: "10px",
  },
  formGroup: {
    marginBottom: "15px",
  },
  label: {
    display: "block",
    marginBottom: "8px",
    color: "#34495e",
    fontWeight: "600",
  },
  select: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d8e0",
    backgroundColor: "white",
  },
  input: {
    width: "100%",
    padding: "10px",
    borderRadius: "6px",
    border: "1px solid #d1d8e0",
  },
  generateButton: {
    backgroundColor: "#3498db",
    color: "white",
    padding: "12px 24px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
  },
  blueprintButton:{
    backgroundColor: "black",
    marginLeft:10,
    color: "white",
    padding: "12px 24px",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    transition: "background-color 0.3s ease",
  },
  actionContainer: {
    textAlign: "center",
    marginTop: "20px",
  },
  topicSelectionContainer: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
  },
  customTopicContainer: {
    display: "flex",
    gap: "10px",
  },
  inputInline: {
    flex: 1,
    padding: "8px",
    borderRadius: "6px",
    border: "1px solid #d1d8e0",
  },
  addButton: {
    backgroundColor: "#2ecc71",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "8px 15px",
  },
  selectedTopicsChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: "8px",
    marginTop: "15px",
  },
  topicChip: {
    backgroundColor: "#e8f4f8",
    padding: "6px 12px",
    borderRadius: "20px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  chipRemoveButton: {
    backgroundColor: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "50%",
    width: "20px",
    height: "20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    marginBottom: 10
  },
  topicConfigDetails: {
    marginTop: "20px",
  },
  topicConfigCard: {
    backgroundColor: "#f9f9fb",
    border: "1px solid #e0e4e8",
    borderRadius: "8px",
    padding: "15px",
    marginBottom: "15px",
  },
  topicConfigHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "15px",
  },
  topicConfigTitle: {
    margin: 0,
    color: "#2c3e50",
  },
  removeTopicButton: {
    backgroundColor: "#e74c3c",
    color: "white",
    border: "none",
    borderRadius: "4px",
    padding: "6px 12px",
  },
  topicConfigGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "10px",
  },
  formGroupInline: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
  },
  inputSmall: {
    padding: "8px",
    borderRadius: "6px",
    border: "1px solid #d1d8e0",
    width: "100%",
  },
  resultContainer: {
    marginTop: "30px",
    backgroundColor: "#f9f9fb",
    padding: "20px",
    borderRadius: "8px",
  },
  resultTitle: {
    color: "#2c3e50",
    borderBottom: "2px solid #3498db",
    paddingBottom: "10px",
  },
  responsePre: {
    backgroundColor: "white",
    border: "1px solid #e0e4e8",
    borderRadius: "6px",
    padding: "15px",
    whiteSpace: "pre-wrap",
    maxHeight: "300px",
    overflowY: "auto",
  },
  downloadButton: {
    backgroundColor: "#2ecc71",
    color: "white",
    border: "none",
    borderRadius: "6px",
    padding: "10px 20px",
    marginTop: "15px",
  },
  weightageContainer: {
    display: "flex",
    justifyContent: "space-between",
    gap: "10px",
  },
  weightageBox: {
    display: "flex",
    flexDirection: "column",
    flex: "1",
  },
};
